"use client";
import { useState } from "react";

const SECRETS = [
  { n: "01", t: "It's an Agent OS, Not a CLI", tag: "architecture",
    p: "Process management, IPC via Unix sockets, scheduled cron jobs, a markdown file system, and 43 user-space tools.",
    d: "The codebase reveals infrastructure comparable to an operating system: process management (6 task types including LocalMainSession, LocalAgentTask, RemoteAgentTask), inter-process communication (SendMessage via Unix Domain Sockets for local, Bridge protocol for cross-machine), scheduled jobs (ScheduleCron), a file system (memdir with ENTRYPOINT.md index), and user-space applications (43 tools). This isn't a chat wrapper — it's a full agent runtime." },
  { n: "02", t: "Memory is Just Markdown Files", tag: "memdir",
    p: "No RAG. No vector embeddings. No Pinecone. Plain markdown in a directory with an index file under 25KB.",
    d: "The memory system (memdir) stores everything as plain markdown files with a ENTRYPOINT.md index. The index must stay under 25KB with one-line entries under 150 characters each. Memory types: user (role/preferences), feedback (corrections), project (ongoing work), reference (external pointers). The sophistication is in Dream Mode's 4-phase consolidation — merge, fix relative dates, delete contradictions, prune stale pointers." },
  { n: "03", t: "Anthropic Uses Claude on Open Source", tag: "undercover",
    p: "Undercover mode automatically activates on public repos. There is NO force-OFF switch. Default is always ON.",
    d: "The undercover system (src/utils/undercover.ts) auto-activates when getRepoClassCached() !== 'internal'. It strips Co-Authored-By lines, model codenames, and any hint of AI involvement. The code comment says: \"Safe default is ON — Claude may push to public remotes from a CWD that isn't itself a git checkout (e.g. /tmp crash repro).\" This means every public PR from an Anthropic employee might have been AI-assisted without anyone knowing." },
  { n: "04", t: "Internal Model Codenames Leaked", tag: "models",
    p: "Capybara, Tengu, Numbat. Plus unreleased versions opus-4-7, sonnet-4-8.",
    d: "Three codenames found: Capybara (encoded via String.fromCharCode to avoid build scanners that grep for it), Tengu (feature flag prefix: tengu_kairos_cron, tengu_hive_evidence), Numbat (\"Remove this section when we launch numbat\" in prompts.ts). The undercover prompt explicitly lists these as forbidden terms. Unreleased model strings: claude-opus-4-7, claude-sonnet-4-8." },
  { n: "05", t: "The Virtual Pet is Real Engineering", tag: "buddy",
    p: "18 species with weighted rarity (1% legendary), ASCII animations, 7 hat types, 6 eye variants, 5 personality stats.",
    d: "CompanionBones (species, eye, hat, shiny, stats) are derived from hash(userId) — deterministic, not random. CompanionSoul (name, personality) is generated by the model on first hatch and stored in config. Rarity weights: common 60, uncommon 25, rare 10, epic 4, legendary 1. Stats: DEBUGGING, PATIENCE, CHAOS, WISDOM, SNARK. The pet \"watches\" your conversation and comments in a speech bubble." },
  { n: "06", t: "It Dreams While You're Away", tag: "dream",
    p: "4-phase memory consolidation during idle: Orient → Gather → Consolidate → Prune.",
    d: "Dream Mode (src/services/autoDream/consolidationPrompt.ts) runs when idle. Phase 1: ls memory dir, read index. Phase 2: check daily logs, grep JSONL transcripts narrowly. Phase 3: merge new into existing, convert relative dates to absolute, delete contradictions. Phase 4: keep index under 25KB, remove stale pointers. The prompt says: \"Don't exhaustively read transcripts. Look only for things you already suspect matter.\"" },
  { n: "07", t: "KAIROS: The Proactive Assistant", tag: "kairos",
    p: "An unreleased system where Claude initiates conversations, runs scheduled tasks, and sends messages unprompted.",
    d: "KAIROS (behind the KAIROS feature flag) enables proactive behavior via BriefTool and SendUserMessage. Combined with ScheduleCron and RemoteTrigger, Claude can run tasks on a schedule, monitor things, and reach out to the user. Related flags: KAIROS_BRIEF (partial), PROACTIVE (earlier iteration), AGENT_TRIGGERS (remote API). This is Claude evolving from a tool you use into an assistant that works alongside you." },
  { n: "08", t: "Internal Build Has Stricter Rules", tag: "internal",
    p: "\"Default to NO comments.\" \"≤25 words between tool calls.\" Mandatory verification for 3+ file edits.",
    d: "The internal build (USER_TYPE === 'ant') adds: ≤25 words between tool calls, ≤100 words final responses, \"default to NO comments — only add when the WHY is non-obvious\", mandatory verification agent for 3+ file edits, \"never claim all tests pass when output shows failures\", internal-only skills (/commit, /simplify, /commit-push-pr). This is why Claude Code feels concise — internally they enforce even stricter limits." },
  { n: "09", t: "Species Names Are Obfuscated", tag: "obfuscation",
    p: "All 18 species encoded via String.fromCharCode() hex because Capybara collides with a model codename scanner.",
    d: "From types.ts: \"One species name collides with a model-codename canary in excluded-strings.txt. The check greps build output (not source), so runtime-constructing the value keeps the literal out of the bundle while the check stays armed for the actual codename.\" Example: capybara = String.fromCharCode(0x63, 0x61, 0x70, 0x79, 0x62, 0x61, 0x72, 0x61). ALL 18 species are encoded this way for uniformity." },
  { n: "10", t: "Multi-Agent Teams via Shared Tasks", tag: "coordinator",
    p: "Agents coordinate through shared task lists, not direct calls. Role-based: read-only (Explore, Plan) vs full-capability.",
    d: "TeamCreate creates a team with a shared task list. TaskCreate/TaskGet/TaskUpdate/TaskOutput provide CRUD. Agents are role-based — read-only agents (Explore, Plan) physically cannot break your code. Communication: SendMessage over Unix Domain Sockets (uds:/path/to.sock for local) or Bridge protocol (bridge:session_01AbCd for cross-machine). Messages arrive as <cross-session-message> XML tags. Discovery via ListPeers." },
];

export default function Secrets() {
  const [open, setOpen] = useState<string | null>(null);
  return (
    <section id="secrets" className="py-20 bg-surface2">
      <div className="max-w-6xl mx-auto px-5">
        <div className="text-xs font-mono font-semibold text-brand uppercase tracking-widest mb-1">Key Findings</div>
        <h2 className="font-mono text-3xl md:text-4xl font-bold mb-2">10 Biggest Secrets</h2>
        <p className="text-text2 mb-8">Click any card to expand the full finding with source code evidence.</p>

        <div className="grid md:grid-cols-2 gap-3">
          {SECRETS.map(s => {
            const isOpen = open === s.n;
            return (
              <div key={s.n}
                className={`bg-white border rounded-xl overflow-hidden cursor-pointer transition-all hover:shadow-md ${isOpen ? "border-brand shadow-md" : "border-border"}`}
                onClick={() => setOpen(isOpen ? null : s.n)}>
                <div className="p-5">
                  <div className="flex items-start justify-between gap-2">
                    <div>
                      <div className="flex items-center gap-2 mb-1">
                        <span className="font-mono text-xs text-brand/50">{s.n}</span>
                        <span className="font-mono text-[10px] px-1.5 py-0.5 bg-brand-bg text-brand rounded">{s.tag}</span>
                      </div>
                      <h3 className="font-mono font-bold text-sm">{s.t}</h3>
                      <p className="text-text2 text-sm mt-1">{s.p}</p>
                    </div>
                    <span className={`text-text3 transition-transform text-xs mt-1 ${isOpen ? "rotate-180" : ""}`}>&#9660;</span>
                  </div>
                </div>
                <div className={`overflow-hidden transition-all duration-300 ${isOpen ? "max-h-[500px]" : "max-h-0"}`}>
                  <div className="px-5 pb-5 pt-0">
                    <div className="border-t border-border pt-4 text-sm text-text2 leading-relaxed">{s.d}</div>
                  </div>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
